name: Upload IPA to TestFlight

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: macos-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Ruby (3.1.4)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.4
          bundler-cache: true

      # ðŸ§© Installer une version stable de fastlane compatible OpenSSL
      - name: Install compatible Fastlane
        run: |
          sudo gem uninstall fastlane -aIx || true
          sudo gem install fastlane -v 2.214.0 --no-document

      - name: Verify versions
        run: |
          ruby -v
          openssl version
          fastlane --version

      - name: Upload IPA to TestFlight
        run: |
          fastlane pilot upload \
            --ipa ./build/PrivilegeClub.ipa \
            --api_key_path ./AppStoreConnectKey.json \
            --skip_waiting_for_build_processing true
