name: Upload IPA to TestFlight

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: macos-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      # ⚙️ Utiliser Ruby 3.1.x (plus stable avec Fastlane/OpenSSL)
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.4
          bundler-cache: true

      - name: Install latest Fastlane
        run: sudo gem install fastlane --no-document

      - name: Upload IPA to TestFlight
        run: |
          fastlane pilot upload \
            --ipa ./build/PrivilegeClub.ipa \
            --api_key_path ./AppStoreConnectKey.json \
            --skip_waiting_for_build_processing true
