name: Upload IPA to TestFlight

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: macos-latest

    env:
      APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
      APP_STORE_CONNECT_API_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Ruby (3.1.4)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.4

      - name: Install Fastlane
        run: sudo gem install fastlane
        
      - name: CrÃ©er le fichier AuthKey.p8
        run: |
          echo "${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}" | base64 --decode > AuthKey.p8
        shell: bash
        
      - name: Verify versions
        run: |
          ruby -v
          fastlane -v

      - name: Upload IPA to TestFlight
        run: |
          fastlane upload
